name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Ajusta la hora UTC a tu preferencia
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # no usar credenciales automáticas
          token: ${{ secrets.PAT }}  # usar tu PAT directamente

      # 2. Actualizar daily.txt
      - name: Update daily file
        run: echo "Update on $(date)" >> daily.txt

      # 3. Configurar Git
      - name: Configure Git
        run: |
          git config --global user.name "AndresContreras1034"
          git config --global user.email "contrerandres001@gmail.com"

      # 4. Commit
      - name: Commit changes
        run: |
          git add daily.txt
          git commit -m "Daily commit $(date)" || echo "No changes to commit"

      # 5. Push
      - name: Push changes
        run: git push origin main
