name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      # Clonar repo usando el PAT
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      # Actualizar archivo daily.txt
      - name: Update daily file
        run: echo "Update on $(date)" >> daily.txt

      # Configurar Git
      - name: Configure Git
        run: |
          git config --global user.name "AndresContreras1034"
          git config --global user.email "contrerandres001@gmail.com"

      # Commit si hay cambios
      - name: Commit changes
        run: |
          git add daily.txt
          git commit -m "Daily commit $(date)" || echo "No changes to commit"

      # Push
      - name: Push changes
        run: git push origin main
